 # Getting & cleaning data : course project
version 1.0

This project uses the data from this study : Human Activity Recognition Using Smartphones Dataset (1) 

The purpose of the projec is to create a tidy dataset for the by subject, by activity with a mean for each feature measurement.

## Data Set information
Detailed information of the methods for performing the measurements can be found in at http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones
For each record in the dataset it is provided:
* Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
* Triaxial Angular velocity from the gyroscope.
* A 561-feature vector with time and frequency domain variables.
* Its activity label.
* An identifier of the subject who carried out the experiment.

The structure for the data 

-+- test
 |   +  Inertial Signals  (not used)
 |
-+- train
 |   +  Inertial Signals  (not used)
 |
 +- activity_labels.txt     Links the class labels with their 
 |                          activity name.
 +- features_info.txt       Shows information about the variables used 
 |                          on the feature vector
 +- features.txt            List of all features.
 |
 |- analysis.csv            results of the analysis
 |- subject_test.txt        Each row identifies the subject who 
 |                          performed the activity
 |- X_test.txt              Test set
 |- y_test.txt              test labels
 |- subject_train.txt       Each row identifies the subject who 
 |                          performed the activity
 |- X_train.txt             Training set
 |- y_train.txt             Training labels
 |
 +- tidy
     |- README.rmd
     |- code-book.rmd       
     |- run_analysis.R      R script to process the data

### Use
Once the data is in the structure above set the working directory to the root of the directory structure show. Execute the `run_analysis.R` script. The tidy data set will be place in a file `analysis.txt`.


Notes: 
======
- Features are normalized and bounded within [-1,1].
- Each feature vector is a row on the text file.
- txt files are space delimited
- subject_??.txt has a range is from 1 to 30.


**1** Human Activity Recognition Using Smartphones Dataset
Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones
